// ---------------------------------------------------------------------------
// ALL personal content lives here (and only here). Everything below is a
// placeholder in [BRACKETS] — fill it in from the admin dashboard at /admin,
// or edit these defaults and press "Reset experience" to re-seed.
// ---------------------------------------------------------------------------
export function seedState() {
  const now = new Date().toISOString();
  return {
    version: 1,
    meta: { createdAt: now, updatedAt: now, resetAt: null },
    vault: { unlocked: false, unlockedAt: null },
    itinerary: [
      {
        id: 'metro',
        time: '11:30',
        title: 'Metro pickup',
        desc: 'Mission control arrives by rail. Look for the agent trying to act casual.',
        icon: '🚇',
        location: '[METRO STATION]',
        stamp: 'DEPARTED',
        isSurprise: false,
        locked: false,
        unlockAt: null,
        unlockedAt: now,
      },
      {
        id: 'checkin',
        time: '12:00',
        title: 'Room check-in',
        desc: 'Drop the bags, claim the good side of the bed, judge the view.',
        icon: '🏨',
        location: '[STAY / HOTEL]',
        stamp: 'CHECKED IN',
        isSurprise: true,
        locked: true,
        unlockAt: null,
        unlockedAt: null,
      },
      {
        id: 'lunch',
        time: '13:00',
        title: 'Lunch',
        desc: 'Refuel. Order too much. The no-regrets policy applies.',
        icon: '🍜',
        location: '[LUNCH SPOT]',
        stamp: 'FUELED UP',
        isSurprise: true,
        locked: true,
        unlockAt: null,
        unlockedAt: null,
      },
      {
        id: 'moviebreak',
        time: '13:30',
        title: 'Movie break',
        desc: 'Back to the room, blanket deployed until five. The vault below decides what we watch.',
        icon: '🍿',
        location: '',
        stamp: 'ROLLING',
        isSurprise: false,
        locked: false,
        unlockAt: null,
        unlockedAt: now,
      },
      {
        id: 'cafe',
        time: '17:00',
        title: 'Café',
        desc: 'Coordinates classified. Mandatory caffeine, strategically unnecessary pastries.',
        icon: '☕',
        location: '[CAFÉ — name it in /admin, then untick “locked”]',
        stamp: 'BREWING',
        isSurprise: true,
        locked: true,
        unlockAt: null,
        unlockedAt: null,
      },
      {
        id: 'comedy',
        time: '20:00',
        title: 'Comedy show',
        desc: 'Professional funny people. Your laugh will be the loudest and that is fine.',
        icon: '🎤',
        location: '[COMEDY VENUE]',
        stamp: 'FRONT ROW',
        isSurprise: true,
        locked: true,
        unlockAt: null,
        unlockedAt: null,
      },
      {
        id: 'home',
        time: '22:00',
        title: 'Back by 10',
        desc: 'Back to the room before the streetlights get judgmental.',
        icon: '🌙',
        location: '',
        stamp: 'ON TRACK',
        isSurprise: false,
        locked: false,
        unlockAt: null,
        unlockedAt: now,
      },
    ],
    challenge: {
      title: 'Side quest',
      desc: '[CHALLENGE — e.g. “Somewhere along the route I hid a tiny thing for you. Find it.”]',
      locked: false,
    },
    // null until she submits; then { note, submittedAt, status, reviewedAt, approvedAt }
    submission: null,
    movies: [
      { id: 'm1', title: '[MOVIE ONE]', genre: '[genre]', duration: '[runtime]', note: '[a one-line personal note]', poster: '' },
      { id: 'm2', title: '[MOVIE TWO]', genre: '[genre]', duration: '[runtime]', note: '[a one-line personal note]', poster: '' },
      { id: 'm3', title: '[MOVIE THREE]', genre: '[genre]', duration: '[runtime]', note: '[a one-line personal note]', poster: '' },
    ],
    // null until she picks; then { movieId, selectedAt }
    selection: null,
  };
}
